<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\ERP.Application.Abstractions\ERP.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\Infrastructure\ERP.Infrastructure\ERP.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\ERP.Persistence\ERP.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.0" />
  </ItemGroup>

</Project>